update readme
BlockchainEtSociete/DevFest_CodeLabs pull request #41
Opened 2023-10-08 09:34 UTC by vinc-developer

2023-10-09 06:48 UTC, devsheder commented on README.md
>  $ npx hardhat clean
@vinc-developer cette commande n'est plus utile pour moi

2023-10-09 06:48 UTC, devsheder commented on README.md
>  $ npx hardhat clean
sinon c'est ok :D

2023-10-09 07:33 UTC, devsheder requested changes, later dismissed

2023-10-09 07:33 UTC, devsheder commented on README.md
>  #### Compile smart contrat
@vinc-developer  juste en dessous : `cd blockchain`

2023-10-09 07:33 UTC, devsheder commented on README.md
> +Config :
@vinc-developer un peu plus haut : la table des matières n'est pas à jour sur la partie blockchain

2023-10-09 19:14 UTC, bpresles commented on README.md
>  $ npx hardhat clean
J'ai modifié la commande de clean dans ma PR pour que ça passe par un script dans package.json et donc par npm.

2023-10-12 11:33 UTC, bpresles approved these changes

2023-10-12 16:05 UTC, merged